version: '3'
services:

  postgres:
    image: postgres:12
    environment:
      POSTGRES_DB: ${postgresql_database}
      POSTGRES_USER: ${postgresql_user}
      POSTGRES_PASSWORD: ${postgresql_password}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
